# --- Part Two ---
#
# With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the
# teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold -
# it's a quantum tachyon manifold.
#
# With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes
# both the left and right path of each splitter encountered.
#
# Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time
# a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in
# the other timeline, the particle went right.
#
# To fix the manifold, what you really need to know is the number of timelines active after a single particle completes
# all of its possible journeys through the manifold.
#
# In the above example, there are many timelines. For instance, there's the timeline where the particle always went
# left:
#
# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ...|^.^...^....
# ...|...........
# ..|^.^...^.^...
# ..|............
# .|^...^.....^..
# .|.............
# |^.^.^.^.^...^.
# |..............
#
# Or, there's the timeline where the particle alternated going left and right at each splitter:
#
# .......S.......
# .......|.......
# ......|^.......
# ......|........
# ......^|^......
# .......|.......
# .....^|^.^.....
# ......|........
# ....^.^|..^....
# .......|.......
# ...^.^.|.^.^...
# .......|.......
# ..^...^|....^..
# .......|.......
# .^.^.^|^.^...^.
# ......|........
#
# Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally
# different path to get there:
#
# .......S.......
# .......|.......
# ......|^.......
# ......|........
# .....|^.^......
# .....|.........
# ....|^.^.^.....
# ....|..........
# ....^|^...^....
# .....|.........
# ...^.^|..^.^...
# ......|........
# ..^..|^.....^..
# .....|.........
# .^.^.^|^.^...^.
# ......|........
#
# In this example, in total, the particle ends up on 40 different timelines.
#
# Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many
# different timelines would a single tachyon particle end up on?

import sys

if __name__ == "__main__":
    # manifold piped to sys.stdin
    manifold = []
    if not sys.stdin.isatty():
        for line in sys.stdin:
            manifold.append(list(line.strip()))
    # main loop (this is dynamic programming, very similar to Project Euler #67)\
    # 'ways' stores the number of paths you need to take to reach a certain position
    # in a row. We update it row by row. First, let's initialize with 0s except under S:
    ways = [0] * len(manifold[0])
    for i, value in enumerate(manifold[0]):
        if value == "S":
            ways[i] = 1
    # Loop starting on 2nd row
    for i_prev, row in enumerate(manifold[1:]):
        old_ways = ways[:]  # copy previous row's ways to transfer to new row
        for j, value in enumerate(row):
            if value == "^":
                ways[j] = 0  # can't reach a split
                if j > 0:
                    ways[j-1] += old_ways[j]
                if j < len(manifold[0]) - 1:
                    ways[j+1] += old_ways[j]
        # print(ways, "".join(row))
    print(sum(ways))
